#!/bin/bash

create_bind_key_dir() {
  mkdir -p ${KEYS_DIR?}
  chmod -R 0775 ${KEYS_DIR?}
  chown -R ${BIND_USER}:${BIND_USER} ${KEYS_DIR?}

  # move keys into new keys directory
  cp -a /etc/keys ${KEYS_DIR?}/keys
}
